### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by RockChinQ** [RockChinQ/Campux#1]
## 前后端功能

- [x] 弹窗公告、投稿规则、顶部banner的展示
- [x] 稿件主动取消投递
- [x] 稿件审核通道
- [ ] 稿件撤回请求、管理员审批
- [ ] 反馈工单
- [x] 可信端鉴权
- [x] 用户组鉴权
- [x] 账号信息管理（改密码什么的
- [x] OAuth和app申请渠道
- [x] 服务列表和跳转

**Comment by RockChinQ** [comment]
## 前端优化

- [x] 稿件按照状态区分颜色
- [x] 匿名稿件显示投稿人QQ号，但标注一个 匿名
- [x] 账户当前有待审核 稿件时，不准投稿
- [x] 首页头像默认（加载前）换成其他的
- [x] 审核稿件页面，进入时自动刷新
- [x] 你的稿件 页，应该是“取消” 而不是“撤回”
